#ifndef POPULATION_H
#define POPULATION_H
//相当于只有第一个源文件，才会执行编译中间的内容

#include "Individual.h"
#include "LocalSearch.h"
#include "Split.h"
#include "Initial.h"
#include "GES.h"
#include "ALNSInitial.h"
#include "DestoryAndRepair.h"
#include <algorithm>

typedef std::vector <Individual*> SubPopulation ;	//起一个别名

class Population
{
   private:

   Params & params ;							// Problem parameters
   Split & split;								// Split algorithm
   Initial & initial;							// Initial population generator
   LocalSearch & localSearch;					// Local search structure
   DestoryAndRepair & destoryAndRepair;
   GES& ges;
   SubPopulation feasibleSubpop;			    // Feasible subpopulation, kept ordered by increasing penalized cost，递增排序，按照惩罚的费用
   SubPopulation infeasibleSubpop;		        // Infeasible subpopulation, kept ordered by increasing penalized cost
   std::list <bool> listFeasibilityLoad ;		// Load feasibility of recent individuals generated by LS，存储bool类型时更加高效
   std::list <bool> listFeasibilityDuration ;	// Duration feasibility of recent individuals generated by LS
   std::vector<std::pair<clock_t, double>> searchProgress; // Keeps tracks of the time stamps of successive best solutions，记录了每次最优的时间戳
   Individual bestSolutionRestart;              // Best solution found during the current restart of the algorithm，当前
   Individual bestSolutionOverall;              // Best solution found during the complete execution of the algorithm，全局
  
   

   // Evaluates the biased fitness of all individuals in the population
   void updateBiasedFitnesses(SubPopulation & pop);

   // Removes the worst individual in terms of biased fitness
   void removeWorstBiasedFitness(SubPopulation & subpop);

   public:
   std::vector<std::vector<int>> LCSe;          //好的序列
   std::vector<std::vector<int>> LCSeHis;          //好的序列
   std::vector<std::vector<int>> LCSi;          //坏的序列
   std::vector<std::vector<int>> LCSiHis;          //坏的序列
   // Creates an initial population of individuals
   void generatePopulation();
   void generateALNSPopulation();

   // Add an individual in the population (survivor selection is automatically triggered whenever the population reaches its maximum size)
   // Returns TRUE if a new best solution of the run has been found
   bool addIndividual (const Individual & indiv, bool updateFeasible);

   std::vector<int> lcs_two(const std::vector<int>& a, const std::vector<int>& b)
   {
      int m = a.size(), n = b.size();
      std::vector<std::vector<int>> dp(m+1, std::vector<int>(n+1, 0));
      // 计算LCS长度
      for(int i=1; i<=m; ++i)
         for(int j=1; j<=n; ++j)
               if(a[i-1]==b[j-1]) dp[i][j]=dp[i-1][j-1]+1;     //这边保存的应该是位置
               else dp[i][j]=std::max(dp[i-1][j], dp[i][j-1]);
      // 回溯找LCS内容
      std::vector<int> lcs;
      int i=m, j=n;
      while(i>0 && j>0) 
      {
         if(a[i-1]==b[j-1]) 
         { lcs.push_back(a[i-1]); --i; --j; }
         else if(dp[i-1][j]>dp[i][j-1]) --i;
         else --j;
      }
      std::reverse(lcs.begin(), lcs.end());
      return lcs;
   }

   void findEliteLCS(const SubPopulation& pop);
   // Cleans all solutions and generates a new initial population (only used when running HGS until a time limit, in which case the algorithm restarts until the time limit is reached)
   void restart();

   // Adaptation of the penalty parameters
   void managePenalties();		//惩罚的适应度

   // Select an individal by binary tournament in the union of the feasible and infeasible subpopulations.
   const Individual & getBinaryTournament();	//选择个体

   const SubPopulation & getSubpop(int sym);

   // Accesses the best feasible individual
   const Individual * getBestFeasible();
   const Individual * getBestCarIndiv();

   // Accesses the best infeasible individual
   const Individual * getBestInfeasible();

   // Accesses the best found solution at all time
   const Individual * getBestFound();

   // Prints population state
   void printState(int nbIter, int nbIterNoImprovement);

   // Distance measure between two individuals, used for diversity calculations
   double brokenPairsDistance(const Individual & indiv1, const Individual & indiv2);		//描述两个解之间的距离

   // Returns the average broken pairs distance of this individual with the nbClosest individuals in the population
   double averageBrokenPairsDistanceClosest(const Individual & indiv, int nbClosest);		//描述和当前个体最近的n个解之间的距离

   // Returns the average diversity value among the 50% best individuals in the subpopulation
   double getDiversity(const SubPopulation & pop);
   //获得种群多样性

   // Returns the average solution value among the 50% best individuals in the subpopulation
   double getAverageCost(const SubPopulation & pop);

   // Exports in a file the history of solution improvements
   void exportSearchProgress(std::string fileName, std::string instanceName);

   // Exports an Individual in CVRPLib format
   void exportCVRPLibFormat(const Individual & indiv, std::string fileName);

   // Constructor
   Population(Params & params, Split & split,Initial & initial , LocalSearch & localSearch,DestoryAndRepair& destoryAndRepair,GES& ges);

   // Destructor
   ~Population();
};

#endif
